"""poll table and vote table

Revision ID: 084e4e9612ed
Revises: 9f671c5f6348
Create Date: 2022-04-11 14:56:32.830237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084e4e9612ed'
down_revision = '9f671c5f6348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=120), nullable=True),
    sa.Column('choice_1', sa.String(length=64), nullable=True),
    sa.Column('choice_2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_choice_1'), 'poll', ['choice_1'], unique=False)
    op.create_index(op.f('ix_poll_choice_2'), 'poll', ['choice_2'], unique=False)
    op.create_index(op.f('ix_poll_question'), 'poll', ['question'], unique=True)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_choice', sa.Boolean(), nullable=True),
    sa.Column('poll_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_vote_choice'), 'vote', ['vote_choice'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_vote_choice'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_poll_question'), table_name='poll')
    op.drop_index(op.f('ix_poll_choice_2'), table_name='poll')
    op.drop_index(op.f('ix_poll_choice_1'), table_name='poll')
    op.drop_table('poll')
    # ### end Alembic commands ###
